language: java
jdk:
- openjdk8
sudo: false
cache:
  directories:
    - ~/.m2/repository
before_install:
  - mkdir -p ~/.m2
install:
  - mvn clean package -DskipTests
deploy:
  provider: releases
  api_key:
    secure: GwHGHOueFdS0z02Z8cVc7cGFfFqUqR+QiZ/VrD0h0ssSPgVvMfmljtXLNGoA8oXr6kTwg4vPTDmoj6u7uymsYeUPptMj62MmF+i463Nvw7TMvR5u4XvKHbnrBXEvvizS4swsjpKFDyjm2AgENz7X5y0ekiZ/GfWoj3UwuNBxr1Fg0cW9CDv/10wNi/+sKb6Aotf1beZf5ze9V7nQbGwwptU3E6PYCTzqdYb1ZxKXivOG27UBcYJoJrD1jo0sCmrR7c/T7lbsrRLs2cv6QVZUrfC6D2+gYxlFV6HDGo7hkHHybbxbQ2M9dco0Sw2H0ovcSs/Vy5IsRRH/QLYIvpIiQm15dh8zGijExC7IRa8Hr5iLrDraoiHKBuo2uRFnyXNKpvLu/jldW0kl9ErADgx5m44T44L1s72Ul2/CnQZgNlotndEXSo275GGtgN6CPF+8lEF1VmUgnWgYauDBoraD+eve/uCvtvSgaU6n7EQgmaLP4ldlJgRyU3Yx36Z6Y1XDJDZumbqgqZ9otkHrxmiNyioiG937l27wQWpAXGdyaq5RGsWVfmONxjbsI8VbSgFdw6ay27L/54Th0WucDq3WMSlMTPfyNh9xVA7psRECsSM4A6JWmP7Rea6wAnOLAHInP+R4+xFyGqzcafk7oLMJuFaikhrfAqkjR1gLknrML98=
  file: "target/cas*.war"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: bioatlas/ala-cas-2.0
    all-branches: true
    tags: true